[0m13:05:57.492036 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B05F55E270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B05D4A2850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B05FDF5A90>]}


============================== 13:05:57.505560 | 67c24ced-a327-4858-b2a8-e032d958f704 ==============================
[0m13:05:57.505560 [info ] [MainThread]: Running with dbt=1.9.4
[0m13:05:57.506326 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Micha\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init ShopFusion', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:05:57.520260 [debug] [MainThread]: Starter project path: C:\Users\Micha\Documents\dbt_env\Lib\site-packages\dbt\include\starter_project
[0m13:05:57.532415 [info ] [MainThread]: 
Your new dbt project "ShopFusion" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:05:57.533272 [info ] [MainThread]: Setting up your profile.
[0m13:08:48.677966 [info ] [MainThread]: Profile ShopFusion written to C:\Users\Micha\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m13:08:48.679365 [debug] [MainThread]: Command `dbt init` succeeded at 13:08:48.679173 after 171.41 seconds
[0m13:08:48.679744 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B06135EB10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B0613AF1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B061113570>]}
[0m13:08:48.680152 [debug] [MainThread]: Flushing usage events
[0m13:08:49.150207 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:08:58.297880 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025983052270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000259820A2850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000259838F1A90>]}


============================== 13:08:58.301137 | 942f0af6-511d-47e4-b132-875115b58116 ==============================
[0m13:08:58.301137 [info ] [MainThread]: Running with dbt=1.9.4
[0m13:08:58.301927 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Micha\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:08:58.327841 [info ] [MainThread]: dbt version: 1.9.4
[0m13:08:58.328569 [info ] [MainThread]: python version: 3.13.3
[0m13:08:58.329148 [info ] [MainThread]: python path: C:\Users\Micha\Documents\dbt_env\Scripts\python.exe
[0m13:08:58.329697 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m13:08:58.378994 [info ] [MainThread]: Using profiles dir at C:\Users\Micha\.dbt
[0m13:08:58.379675 [info ] [MainThread]: Using profiles.yml file at C:\Users\Micha\.dbt\profiles.yml
[0m13:08:58.380250 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Micha\Documents\BI_Dev-E-commerce_Sales_Analytics\dbt_project.yml
[0m13:08:58.380890 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m13:08:58.382237 [debug] [MainThread]: Command `dbt debug` failed at 13:08:58.382042 after 0.30 seconds
[0m13:08:58.382601 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025983F70050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025983F51010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025983F74270>]}
[0m13:08:58.382885 [debug] [MainThread]: Flushing usage events
[0m13:08:58.844958 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:23:50.674308 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017957A56270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017954982850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000179592F5A90>]}


============================== 13:23:50.677551 | 7da7114e-eee9-4311-af13-3105469d79af ==============================
[0m13:23:50.677551 [info ] [MainThread]: Running with dbt=1.9.4
[0m13:23:50.678308 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Micha\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m13:23:50.689454 [info ] [MainThread]: dbt version: 1.9.4
[0m13:23:50.690075 [info ] [MainThread]: python version: 3.13.3
[0m13:23:50.690674 [info ] [MainThread]: python path: C:\Users\Micha\Documents\dbt_env\Scripts\python.exe
[0m13:23:50.691229 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m13:23:50.745916 [info ] [MainThread]: Using profiles dir at C:\Users\Micha\.dbt
[0m13:23:50.746464 [info ] [MainThread]: Using profiles.yml file at C:\Users\Micha\.dbt\profiles.yml
[0m13:23:50.746937 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Micha\Documents\BI_Dev-E-commerce_Sales_Analytics\dbt_project.yml
[0m13:23:50.747420 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m13:23:50.748192 [debug] [MainThread]: Command `dbt debug` failed at 13:23:50.748084 after 0.23 seconds
[0m13:23:50.748486 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017959974050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001795994D010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017959970270>]}
[0m13:23:50.748832 [debug] [MainThread]: Flushing usage events
[0m13:23:51.192117 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:24:44.535133 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025D25DAE270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025D22D82850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025D26645A90>]}


============================== 13:24:44.538453 | 6af8c2be-6a13-4dfc-b6e0-afc59e251057 ==============================
[0m13:24:44.538453 [info ] [MainThread]: Running with dbt=1.9.4
[0m13:24:44.539162 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Micha\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:24:44.549104 [info ] [MainThread]: dbt version: 1.9.4
[0m13:24:44.549761 [info ] [MainThread]: python version: 3.13.3
[0m13:24:44.550290 [info ] [MainThread]: python path: C:\Users\Micha\Documents\dbt_env\Scripts\python.exe
[0m13:24:44.550827 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m13:24:44.601946 [info ] [MainThread]: Using profiles dir at C:\Users\Micha\.dbt
[0m13:24:44.602633 [info ] [MainThread]: Using profiles.yml file at C:\Users\Micha\.dbt\profiles.yml
[0m13:24:44.603207 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Micha\Documents\BI_Dev-E-commerce_Sales_Analytics\dbt_project.yml
[0m13:24:44.603738 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m13:24:44.604543 [debug] [MainThread]: Command `dbt debug` failed at 13:24:44.604445 after 0.18 seconds
[0m13:24:44.604811 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025D26CE0050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025D26CBD010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025D26CE4270>]}
[0m13:24:44.605076 [debug] [MainThread]: Flushing usage events
[0m13:24:45.089909 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:26:05.036818 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002844AA86270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028447A62850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002844C3F5A90>]}


============================== 13:26:05.040091 | 43d862f3-5d8e-4333-894d-90946ec139db ==============================
[0m13:26:05.040091 [info ] [MainThread]: Running with dbt=1.9.4
[0m13:26:05.040819 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Micha\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:26:05.051865 [info ] [MainThread]: dbt version: 1.9.4
[0m13:26:05.052556 [info ] [MainThread]: python version: 3.13.3
[0m13:26:05.053170 [info ] [MainThread]: python path: C:\Users\Micha\Documents\dbt_env\Scripts\python.exe
[0m13:26:05.053672 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m13:26:05.104050 [info ] [MainThread]: Using profiles dir at C:\Users\Micha\.dbt
[0m13:26:05.104753 [info ] [MainThread]: Using profiles.yml file at C:\Users\Micha\.dbt\profiles.yml
[0m13:26:05.105164 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Micha\Documents\BI_Dev-E-commerce_Sales_Analytics\dbt_project.yml
[0m13:26:05.113168 [info ] [MainThread]: adapter type: postgres
[0m13:26:05.113710 [info ] [MainThread]: adapter version: 1.9.0
[0m13:26:05.114588 [info ] [MainThread]: Configuration:
[0m13:26:05.115149 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m13:26:05.115709 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m13:26:05.116235 [info ] [MainThread]: Required dependencies:
[0m13:26:05.116716 [debug] [MainThread]: Executing "git --help"
[0m13:26:05.129552 [info ] [MainThread]:  - git [[31mERROR[0m]

[0m13:26:05.130226 [info ] [MainThread]: Connection:
[0m13:26:05.130823 [info ] [MainThread]:   host: ep-quiet-forest-absqal98-pooler.eu-west-2.aws.neon.tech
[0m13:26:05.131261 [info ] [MainThread]:   port: 5432
[0m13:26:05.131748 [info ] [MainThread]:   user: TechLink_owner
[0m13:26:05.132269 [info ] [MainThread]:   database: TechLink
[0m13:26:05.132616 [info ] [MainThread]:   schema: public
[0m13:26:05.133134 [info ] [MainThread]:   connect_timeout: 10
[0m13:26:05.133652 [info ] [MainThread]:   role: None
[0m13:26:05.134325 [info ] [MainThread]:   search_path: None
[0m13:26:05.135078 [info ] [MainThread]:   keepalives_idle: 0
[0m13:26:05.135579 [info ] [MainThread]:   sslmode: None
[0m13:26:05.136286 [info ] [MainThread]:   sslcert: None
[0m13:26:05.136769 [info ] [MainThread]:   sslkey: None
[0m13:26:05.137241 [info ] [MainThread]:   sslrootcert: None
[0m13:26:05.137719 [info ] [MainThread]:   application_name: dbt
[0m13:26:05.138087 [info ] [MainThread]:   retries: 1
[0m13:26:05.138597 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m13:26:05.308479 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m13:26:07.467309 [debug] [MainThread]: Using postgres connection "debug"
[0m13:26:07.467656 [debug] [MainThread]: On debug: select 1 as id
[0m13:26:07.467900 [debug] [MainThread]: Opening a new connection, currently in state init
[0m13:26:07.743261 [debug] [MainThread]: SQL status: SELECT 1 in 0.275 seconds
[0m13:26:07.744681 [debug] [MainThread]: On debug: Close
[0m13:26:07.745464 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m13:26:07.746147 [info ] [MainThread]: [31m2 checks failed:[0m
[0m13:26:07.746676 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\Micha\Documents\BI_Dev-E-commerce_Sales_Analytics\dbt_project.yml> not found

[0m13:26:07.747183 [info ] [MainThread]: Error from git --help: Could not find command, ensure it is in the user's PATH and that the user has permissions to run it: "git"

[0m13:26:07.748065 [debug] [MainThread]: Command `dbt debug` failed at 13:26:07.747947 after 2.82 seconds
[0m13:26:07.748371 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m13:26:07.748663 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002844CD2D6E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002844CA532F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002844C927CE0>]}
[0m13:26:07.749000 [debug] [MainThread]: Flushing usage events
[0m13:26:08.218816 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:11:37.850204 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014E1B256270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014E1A2A2850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014E1BAF5A90>]}


============================== 14:11:37.853554 | 19d03d7c-3abc-42e8-a433-a51498917691 ==============================
[0m14:11:37.853554 [info ] [MainThread]: Running with dbt=1.9.4
[0m14:11:37.854259 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Micha\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt test', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:11:37.854640 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Micha\Documents\BI_Dev-E-commerce_Sales_Analytics\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:11:37.855448 [debug] [MainThread]: Command `dbt test` failed at 14:11:37.855356 after 0.23 seconds
[0m14:11:37.855707 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014E1BED6FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014E1BE479B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000014E1BE13BD0>]}
[0m14:11:37.855957 [debug] [MainThread]: Flushing usage events
[0m14:11:38.314393 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:11:44.462838 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C283A56270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C280A02850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C2852F5A90>]}


============================== 14:11:44.466359 | bbc24259-8472-4f74-961d-2197030c66e2 ==============================
[0m14:11:44.466359 [info ] [MainThread]: Running with dbt=1.9.4
[0m14:11:44.467175 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Micha\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:11:44.467600 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Micha\Documents\BI_Dev-E-commerce_Sales_Analytics\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:11:44.468514 [debug] [MainThread]: Command `dbt run` failed at 14:11:44.468409 after 0.13 seconds
[0m14:11:44.468823 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C2856D6FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C28563B9B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C285613BD0>]}
[0m14:11:44.469117 [debug] [MainThread]: Flushing usage events
[0m14:11:44.912193 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:11:56.665268 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AF55A7E270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AF52A52850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AF573F5A90>]}


============================== 14:11:56.668424 | bc6d5e22-bc21-4610-a403-ae866b1c7b84 ==============================
[0m14:11:56.668424 [info ] [MainThread]: Running with dbt=1.9.4
[0m14:11:56.669191 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Micha\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m14:11:56.679075 [info ] [MainThread]: dbt version: 1.9.4
[0m14:11:56.679659 [info ] [MainThread]: python version: 3.13.3
[0m14:11:56.680177 [info ] [MainThread]: python path: C:\Users\Micha\Documents\dbt_env\Scripts\python.exe
[0m14:11:56.680632 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m14:11:56.732756 [info ] [MainThread]: Using profiles dir at C:\Users\Micha\.dbt
[0m14:11:56.733492 [info ] [MainThread]: Using profiles.yml file at C:\Users\Micha\.dbt\profiles.yml
[0m14:11:56.733962 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Micha\Documents\BI_Dev-E-commerce_Sales_Analytics\dbt_project.yml
[0m14:11:56.734758 [info ] [MainThread]: adapter type: postgres
[0m14:11:56.735185 [info ] [MainThread]: adapter version: 1.9.0
[0m14:11:56.735703 [info ] [MainThread]: Configuration:
[0m14:11:56.736089 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m14:11:56.736523 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m14:11:56.736919 [info ] [MainThread]: Required dependencies:
[0m14:11:56.737261 [debug] [MainThread]: Executing "git --help"
[0m14:11:56.740253 [info ] [MainThread]:  - git [[31mERROR[0m]

[0m14:11:56.740676 [info ] [MainThread]: Connection:
[0m14:11:56.741156 [info ] [MainThread]:   host: ep-quiet-forest-absqal98-pooler.eu-west-2.aws.neon.tech
[0m14:11:56.741615 [info ] [MainThread]:   port: 5432
[0m14:11:56.742138 [info ] [MainThread]:   user: TechLink_owner
[0m14:11:56.742638 [info ] [MainThread]:   database: TechLink
[0m14:11:56.743109 [info ] [MainThread]:   schema: public
[0m14:11:56.743458 [info ] [MainThread]:   connect_timeout: 10
[0m14:11:56.743873 [info ] [MainThread]:   role: None
[0m14:11:56.744333 [info ] [MainThread]:   search_path: None
[0m14:11:56.744706 [info ] [MainThread]:   keepalives_idle: 0
[0m14:11:56.745050 [info ] [MainThread]:   sslmode: None
[0m14:11:56.745431 [info ] [MainThread]:   sslcert: None
[0m14:11:56.745857 [info ] [MainThread]:   sslkey: None
[0m14:11:56.746361 [info ] [MainThread]:   sslrootcert: None
[0m14:11:56.746788 [info ] [MainThread]:   application_name: dbt
[0m14:11:56.747222 [info ] [MainThread]:   retries: 1
[0m14:11:56.748198 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m14:11:56.910036 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m14:11:56.950926 [debug] [MainThread]: Using postgres connection "debug"
[0m14:11:56.951253 [debug] [MainThread]: On debug: select 1 as id
[0m14:11:56.951467 [debug] [MainThread]: Opening a new connection, currently in state init
[0m14:11:57.256692 [debug] [MainThread]: SQL status: SELECT 1 in 0.305 seconds
[0m14:11:57.259243 [debug] [MainThread]: On debug: Close
[0m14:11:57.260499 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m14:11:57.262018 [info ] [MainThread]: [31m2 checks failed:[0m
[0m14:11:57.263144 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\Micha\Documents\BI_Dev-E-commerce_Sales_Analytics\dbt_project.yml> not found

[0m14:11:57.264057 [info ] [MainThread]: Error from git --help: Could not find command, ensure it is in the user's PATH and that the user has permissions to run it: "git"

[0m14:11:57.265431 [debug] [MainThread]: Command `dbt debug` failed at 14:11:57.265247 after 0.71 seconds
[0m14:11:57.265870 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m14:11:57.266303 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AF57D2D6E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AF57A532F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AF57927CE0>]}
[0m14:11:57.266783 [debug] [MainThread]: Flushing usage events
[0m14:11:57.704876 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:12:23.197554 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000268A3E52270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000268A0D7A850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000268A46F5A90>]}


============================== 14:12:23.200948 | 1319d9da-5e1e-4e90-99e1-da97ba89a85b ==============================
[0m14:12:23.200948 [info ] [MainThread]: Running with dbt=1.9.4
[0m14:12:23.201712 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Micha\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:12:23.212693 [info ] [MainThread]: dbt version: 1.9.4
[0m14:12:23.213265 [info ] [MainThread]: python version: 3.13.3
[0m14:12:23.213804 [info ] [MainThread]: python path: C:\Users\Micha\Documents\dbt_env\Scripts\python.exe
[0m14:12:23.214562 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m14:12:23.264152 [info ] [MainThread]: Using profiles dir at C:\Users\Micha\.dbt
[0m14:12:23.264954 [info ] [MainThread]: Using profiles.yml file at C:\Users\Micha\.dbt\profiles.yml
[0m14:12:23.265469 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Micha\Documents\BI_Dev-E-commerce_Sales_Analytics\dbt_project.yml
[0m14:12:23.266507 [info ] [MainThread]: adapter type: postgres
[0m14:12:23.267046 [info ] [MainThread]: adapter version: 1.9.0
[0m14:12:23.267592 [info ] [MainThread]: Configuration:
[0m14:12:23.268019 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m14:12:23.268417 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m14:12:23.268863 [info ] [MainThread]: Required dependencies:
[0m14:12:23.269221 [debug] [MainThread]: Executing "git --help"
[0m14:12:23.272590 [info ] [MainThread]:  - git [[31mERROR[0m]

[0m14:12:23.272995 [info ] [MainThread]: Connection:
[0m14:12:23.273435 [info ] [MainThread]:   host: ep-quiet-forest-absqal98-pooler.eu-west-2.aws.neon.tech
[0m14:12:23.273924 [info ] [MainThread]:   port: 5432
[0m14:12:23.274391 [info ] [MainThread]:   user: TechLink_owner
[0m14:12:23.274898 [info ] [MainThread]:   database: TechLink
[0m14:12:23.275324 [info ] [MainThread]:   schema: public
[0m14:12:23.275637 [info ] [MainThread]:   connect_timeout: 10
[0m14:12:23.275915 [info ] [MainThread]:   role: None
[0m14:12:23.276176 [info ] [MainThread]:   search_path: None
[0m14:12:23.276432 [info ] [MainThread]:   keepalives_idle: 0
[0m14:12:23.276675 [info ] [MainThread]:   sslmode: None
[0m14:12:23.277122 [info ] [MainThread]:   sslcert: None
[0m14:12:23.277535 [info ] [MainThread]:   sslkey: None
[0m14:12:23.277904 [info ] [MainThread]:   sslrootcert: None
[0m14:12:23.278334 [info ] [MainThread]:   application_name: dbt
[0m14:12:23.278758 [info ] [MainThread]:   retries: 1
[0m14:12:23.279512 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m14:12:23.444372 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m14:12:23.487201 [debug] [MainThread]: Using postgres connection "debug"
[0m14:12:23.487569 [debug] [MainThread]: On debug: select 1 as id
[0m14:12:23.487830 [debug] [MainThread]: Opening a new connection, currently in state init
[0m14:12:23.671259 [debug] [MainThread]: SQL status: SELECT 1 in 0.183 seconds
[0m14:12:23.673770 [debug] [MainThread]: On debug: Close
[0m14:12:23.675258 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m14:12:23.676593 [info ] [MainThread]: [31m2 checks failed:[0m
[0m14:12:23.677548 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\Micha\Documents\BI_Dev-E-commerce_Sales_Analytics\dbt_project.yml> not found

[0m14:12:23.678467 [info ] [MainThread]: Error from git --help: Could not find command, ensure it is in the user's PATH and that the user has permissions to run it: "git"

[0m14:12:23.679585 [debug] [MainThread]: Command `dbt debug` failed at 14:12:23.679458 after 0.58 seconds
[0m14:12:23.679882 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m14:12:23.680179 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000268A60316E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000268A4D532F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000268A4C27CE0>]}
[0m14:12:23.680588 [debug] [MainThread]: Flushing usage events
[0m14:12:24.138549 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:45:20.398940 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C6785623C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C67648A850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C678DFDA90>]}


============================== 18:45:20.404146 | a2b19081-db85-47d7-abf0-a0fef35ce00b ==============================
[0m18:45:20.404146 [info ] [MainThread]: Running with dbt=1.9.4
[0m18:45:20.404670 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Micha\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:45:20.420585 [info ] [MainThread]: dbt version: 1.9.4
[0m18:45:20.421009 [info ] [MainThread]: python version: 3.13.3
[0m18:45:20.421340 [info ] [MainThread]: python path: E:\BI_Dev-E-commerce_Sales_Analytics\dbt_env\Scripts\python.exe
[0m18:45:20.421610 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m18:45:20.474359 [info ] [MainThread]: Using profiles dir at C:\Users\Micha\.dbt
[0m18:45:20.474839 [info ] [MainThread]: Using profiles.yml file at C:\Users\Micha\.dbt\profiles.yml
[0m18:45:20.475142 [info ] [MainThread]: Using dbt_project.yml file at E:\BI_Dev-E-commerce_Sales_Analytics\dbt_project.yml
[0m18:45:20.475842 [info ] [MainThread]: adapter type: postgres
[0m18:45:20.476180 [info ] [MainThread]: adapter version: 1.9.0
[0m18:45:20.476492 [info ] [MainThread]: Configuration:
[0m18:45:20.476765 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m18:45:20.477050 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m18:45:20.477322 [info ] [MainThread]: Required dependencies:
[0m18:45:20.477599 [debug] [MainThread]: Executing "git --help"
[0m18:45:20.506987 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m18:45:20.507348 [debug] [MainThread]: STDERR: "b''"
[0m18:45:20.507686 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m18:45:20.508053 [info ] [MainThread]: Connection:
[0m18:45:20.508389 [info ] [MainThread]:   host: ep-quiet-forest-absqal98-pooler.eu-west-2.aws.neon.tech
[0m18:45:20.508821 [info ] [MainThread]:   port: 5432
[0m18:45:20.509250 [info ] [MainThread]:   user: TechLink_owner
[0m18:45:20.509597 [info ] [MainThread]:   database: TechLink
[0m18:45:20.509902 [info ] [MainThread]:   schema: public
[0m18:45:20.510191 [info ] [MainThread]:   connect_timeout: 10
[0m18:45:20.510526 [info ] [MainThread]:   role: None
[0m18:45:20.510826 [info ] [MainThread]:   search_path: None
[0m18:45:20.511121 [info ] [MainThread]:   keepalives_idle: 0
[0m18:45:20.511368 [info ] [MainThread]:   sslmode: None
[0m18:45:20.511591 [info ] [MainThread]:   sslcert: None
[0m18:45:20.511817 [info ] [MainThread]:   sslkey: None
[0m18:45:20.512039 [info ] [MainThread]:   sslrootcert: None
[0m18:45:20.512270 [info ] [MainThread]:   application_name: dbt
[0m18:45:20.512476 [info ] [MainThread]:   retries: 1
[0m18:45:20.512820 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m18:45:20.644403 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m18:45:20.701076 [debug] [MainThread]: Using postgres connection "debug"
[0m18:45:20.701369 [debug] [MainThread]: On debug: select 1 as id
[0m18:45:20.701645 [debug] [MainThread]: Opening a new connection, currently in state init
[0m18:45:21.214968 [debug] [MainThread]: SQL status: SELECT 1 in 0.513 seconds
[0m18:45:21.215715 [debug] [MainThread]: On debug: Close
[0m18:45:21.216131 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m18:45:21.216570 [info ] [MainThread]: [31m1 check failed:[0m
[0m18:45:21.216932 [info ] [MainThread]: Project loading failed for the following reason:
 project path <E:\BI_Dev-E-commerce_Sales_Analytics\dbt_project.yml> not found

[0m18:45:21.217497 [debug] [MainThread]: Command `dbt debug` failed at 18:45:21.217414 after 0.92 seconds
[0m18:45:21.217717 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m18:45:21.217941 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C67A758E90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C67A46B0B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C67A521480>]}
[0m18:45:21.218210 [debug] [MainThread]: Flushing usage events
[0m18:45:21.685810 [debug] [MainThread]: An error was encountered while trying to flush usage events
